### ISSUE TITLE
Error while connecting multiple charge points

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [villekr/ocpp-asgi#6]
@villekr Sometimes when my ChargePoint reconnects to my CentralSystem, I get this error, is this a handshake error, and is it necessary that I get an Exception?
How to avoid this or else bypass this? 
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 225, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 100, in __call__
    await self.handler(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 136, in handler
    await self.on_receive(message=context.body, context=context)
  File "/app/ocpp_asgi/app.py", line 181, in on_receive
    await router.route_message(message=message, context=context)
  File "/app/ocpp_asgi/router.py", line 177, in route_message
    await self._handle_call(msg, context=context)
  File "/app/ocpp_asgi/router.py", line 255, in _handle_call
    await self._send(message=response.to_json(), is_response=True, context=context)
  File "/app/ocpp_asgi/router.py", line 307, in _send
    await context.send(message=message, is_response=is_response, context=context)
  File "/app/ocpp_asgi/app.py", line 58, in __call__
    await self.send(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 298, in asgi_send
    await self.send(data)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 632, in send
    await self.write_frame(True, opcode, data)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1189, in write_frame
    await self.drain()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1178, in drain
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
[run_asgi - 229] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 225, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 100, in __call__
    await self.handler(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 136, in handler
    await self.on_receive(message=context.body, context=context)
  File "/app/ocpp_asgi/app.py", line 181, in on_receive
    await router.route_message(message=message, context=context)
  File "/app/ocpp_asgi/router.py", line 177, in route_message
    await self._handle_call(msg, context=context)
  File "/app/ocpp_asgi/router.py", line 255, in _handle_call
    await self._send(message=response.to_json(), is_response=True, context=context)
  File "/app/ocpp_asgi/router.py", line 307, in _send
    await context.send(message=message, is_response=is_response, context=context)
  File "/app/ocpp_asgi/app.py", line 58, in __call__
    await self.send(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 298, in asgi_send
    await self.send(data)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 632, in send
    await self.write_frame(True, opcode, data)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1189, in write_frame
    await self.drain()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1178, in drain
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
DEBUG:    = connection is CLOSED
[connection_lost - 1489] = connection is CLOSED
DEBUG:    ! failing connection with code 1006
[fail_connection - 1404] ! failing connection with code 1006
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 225, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 100, in __call__
    await self.handler(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 136, in handler
    await self.on_receive(message=context.body, context=context)
  File "/app/ocpp_asgi/app.py", line 181, in on_receive
    await router.route_message(message=message, context=context)
  File "/app/ocpp_asgi/router.py", line 177, in route_message
    await self._handle_call(msg, context=context)
  File "/app/ocpp_asgi/router.py", line 255, in _handle_call
    await self._send(message=response.to_json(), is_response=True, context=context)
  File "/app/ocpp_asgi/router.py", line 307, in _send
    await context.send(message=message, is_response=is_response, context=context)
  File "/app/ocpp_asgi/app.py", line 58, in __call__
    await self.send(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 298, in asgi_send
    await self.send(data)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 632, in send
    await self.write_frame(True, opcode, data)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1189, in write_frame
    await self.drain()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1178, in drain
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
[run_asgi - 229] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 225, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 100, in __call__
    await self.handler(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 136, in handler
    await self.on_receive(message=context.body, context=context)
  File "/app/ocpp_asgi/app.py", line 181, in on_receive
    await router.route_message(message=message, context=context)
  File "/app/ocpp_asgi/router.py", line 177, in route_message
    await self._handle_call(msg, context=context)
  File "/app/ocpp_asgi/router.py", line 255, in _handle_call
    await self._send(message=response.to_json(), is_response=True, context=context)
  File "/app/ocpp_asgi/router.py", line 307, in _send
    await context.send(message=message, is_response=is_response, context=context)
  File "/app/ocpp_asgi/app.py", line 58, in __call__
    await self.send(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 298, in asgi_send
    await self.send(data)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 632, in send
    await self.write_frame(True, opcode, data)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1189, in write_frame
    await self.drain()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1178, in drain
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
```

**Comment by ChaitanyaYeole02** [comment]
I am also getting this error randomly

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 100, in __call__
    await self.handler(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 130, in handler
    context: RouterContext = self._create_context(
  File "/app/ocpp_asgi/app.py", line 241, in _create_context
    http_event = json.loads(event["body"])
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[run_asgi - 409] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 100, in __call__
    await self.handler(scope, receive, send)
  File "/app/ocpp_asgi/app.py", line 130, in handler
    context: RouterContext = self._create_context(
  File "/app/ocpp_asgi/app.py", line 241, in _create_context
    http_event = json.loads(event["body"])
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     10.151.2.129:64188 - "GET / HTTP/1.1" 500 Internal Server Error
```

**Comment by ChaitanyaYeole02** [comment]
@villekr Any suggestions?

**Comment by villekr** [comment]
First one looks like there might be some messaging going on during disconnect or over already disconnected connection. Try to be careful how you initiate messaging from on_connect. Also ensure that you update charging station's connection state on on_disconnect so that your backed doesn't try to message to disconnected instance.

Second one might be a bug in ocpp-asgi. Earlier in your logs before traceback error you should have 'scope' variable logged. What's the value in that case?

**Comment by ChaitanyaYeole02** [comment]
I have updated my Charging Station's connection state inside on_disconnect but still, I get this kindof error.
Also, for second error, this is a bug in ocpp-asgi, as when the websocket connection receives an empty HTTP requests it crashes.
As websockets should automatically try to upgrade any HTTP request to WS, and if its not able to do so it should send a 426 upgrade error. I have done these changes.

Inside **__create_context_** I have check if there is any message, if not then returned for None
```
    def _create_context(
        self, *, scope: Scope, event: dict, send: Send
    ) -> RouterContext:
        queue = asyncio.Queue()
        call_lock = asyncio.Lock()
        if scope["type"] == ASGIScope.websocket:
            charging_station_id = scope["path"].strip("/")
            subprotocols = scope["subprotocols"]
            body = event["text"] if "text" in event else None
        else:  # scope["type"] == ASGIScope.http:
            if event["type"] == ASGIHTTPEvent.disconnect:
                # Don't bother creating context for disconnect as it's not used
                return None
            http_event = json.loads(event["body"]) if len(event["body"]) else json.loads('' or '{}')
            if not http_event:
                return None
            http_event_context: HTTPEventContext = self.http_parse_event(http_event)
            charging_station_id = http_event_context.charging_station_id
            subprotocols = http_event_context.subprotocols
            body = http_event_context.body 
```

Inside HTTP and handler, I have check the message, if its empty then it would respond with 426 Upgrade error.
```
    async def handler(self, scope: Scope, receive: Receive, send: Send):
        # try:
        log.debug(f"{scope=}")
        while True:
            event = await receive()

            log.debug(f"{event=}")
            context: RouterContext = self._create_context(
                scope=scope, event=event, send=send
            )

        # WebSocket
            if event["type"] == ASGIWebSocketEvent.receive:
                await self.on_receive(message=context.body, context=context)
            elif event["type"] == ASGIWebSocketEvent.connect:
                response = await self.on_connect(context)
                if response:
                    await send({"type": "websocket.accept"})
                else:
                    await send({"type": "websocket.close"})
            elif event["type"] == ASGIWebSocketEvent.disconnect:
                await self.on_disconnect(
                    charging_station_id=context.charging_station_id,
                    subprotocol=context.subprotocol,
                    code=event["code"],
                )
                break
            # HTTP
            elif event["type"] == ASGIHTTPEvent.request:
                # TODO: handle more_body case
                if context:
                    message_type = int(context.body[1])
                    if message_type != MessageType.Call:
                        # For "CallResult" and "CallError" send empty response back
                        # as ocpp protocol doesn't mandate response for these message types
                        # For "Call" response will be sent by router
                        await send(
                            {"type": ASGIHTTPEvent.response_start.value, "status": 200}
                        )
                        await send({"type": ASGIHTTPEvent.response_body.value})
                    await self.on_receive(message=context.body, context=context)
                else:
                    await send({"type": ASGIHTTPEvent.response_start, "status": 426})
                    await send({"type": ASGIHTTPEvent.response_body.value,
                                "body": b'You cannot access a WebSocket server directly with a browser. '
                                        b'You need a WebSocket client.'})
            elif event["type"] == ASGIHTTPEvent.disconnect.value:
                break
```

**Comment by ChaitanyaYeole02** [comment]
@villekr Please ignore the previous comment. I have created a reproducible example. If you have any doubt about this please let me know. I am just suggesting that the WebSockets library upgrades the HTTP request by itself, then why isn't this happening over here? Is this an ocpp-asgi library error or uvicorn error?

Packages Used
websocket==10.0
ocpp==0.8.3
asyncio=3.4.3

Normal WS Code
```
import asyncio
import logging
import websockets

logging.basicConfig(level=logging.INFO)


async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers[
            'Sec-WebSocket-Protocol']
    except KeyError:
        logging.info("Client hasn't requested any Subprotocol. "
                 "Closing Connection")
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning('Protocols Mismatched | Expected Subprotocols: %s,'
                        ' but client supports  %s | Closing connection',
                        websocket.available_subprotocols,
                        requested_protocols)
        return await websocket.close()


async def main():
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        9000,
        subprotocols=['ocpp2.0.1']
    )
    logging.info("WebSocket Server Started")
    await server.wait_closed()

if __name__ == '__main__':
    asyncio.run(main())
```

Logs after I send an empty HTTP request through Postman `HTTP Request - http://localhost:9000/`

```
INFO:websockets.server:server listening on 0.0.0.0:9000
INFO:root:WebSocket Server Started
INFO:websockets.server:connection failed (426 Upgrade Required)
INFO:websockets.server:connection closed
INFO:websockets.server:connection failed (426 Upgrade Required)
INFO:websockets.server:connection closed
```


Packages Used
websocket==10.0
ocpp==0.8.3
asyncio=3.4.3
uvicorn==0.18.3


Code through OCPP-ASGI

```
import uvicorn

from ocpp_asgi.app import ASGIApplication, RouterContext, Subprotocol
from central_system.routers.v16.provisioning_router import (router as v16_provisioning_router,)


class CentralSystem(ASGIApplication):
    """Central System is collection of routers."""

    async def on_startup(self):
        print("(CentralSystem) Startup.")

    async def on_shutdown(self):
        print("(CentralSystem) Shutdown.")

    async def on_connect(self, context: RouterContext) -> bool:
        print(
            f"(CentralSystem) Charging Station id: {context.charging_station_id} subprotocol: "
            f"{context.subprotocol} connected."
            # noqa: E501
        )
        # You can inspect context.scope["headers"] and perform eg. basic authentication
        return True

    async def on_disconnect(
            self, *, charging_station_id: str, subprotocol: Subprotocol, code: str
    ):
        ocpp_id = charging_station_id
        print(
            f"OCPP ID: {ocpp_id} subprotocol: {subprotocol} "
            f"Disconnected. Reason code: {code}"
        )


central_system = CentralSystem()
central_system.include_router(v16_provisioning_router)
if __name__ == '__main__':
    subprotocols = f"{Subprotocol.ocpp16}"
    headers = [("Sec-WebSocket-Protocol", subprotocols)]
    uvicorn.run("main-2:central_system", host="0.0.0.0", port=9000, headers=headers, workers=1, ws_ping_interval=None,
                ws_ping_timeout=None, use_colors=True, log_level='debug', timeout_keep_alive=30)
```

Logs after I send an empty HTTP request through Postman `HTTP Request - http://localhost:9000/`

```
C:\Users\s******5\PycharmProjects\http-error-ws\venv\Scripts\python.exe C:/Users/s******5/PycharmProjects/http-error-ws/main-2.py 
(CentralSystem) Startup.
INFO:     Started server process [10700]
[serve - 75] Started server process [10700]
INFO:     Waiting for application startup.
[startup - 47] Waiting for application startup.
INFO:     Application startup complete.
[startup - 61] Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
[_log_started_message - 207] Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO:     127.0.0.1:57534 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\s******5\PycharmProjects\http-error-ws\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\s******5\PycharmProjects\http-error-ws\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\s******5\PycharmProjects\http-error-ws\ocpp_asgi\app.py", line 100, in __call__
    await self.handler(scope, receive, send)
  File "C:\Users\s******5\PycharmProjects\http-error-ws\ocpp_asgi\app.py", line 130, in handler
    context: RouterContext = self._create_context(
  File "C:\Users\s******5\PycharmProjects\http-error-ws\ocpp_asgi\app.py", line 232, in _create_context
    http_event = json.loads(event["body"])
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[run_asgi - 409] Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\s******5\PycharmProjects\http-error-ws\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\s******5\PycharmProjects\http-error-ws\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\s******5\PycharmProjects\http-error-ws\ocpp_asgi\app.py", line 100, in __call__
    await self.handler(scope, receive, send)
  File "C:\Users\s******5\PycharmProjects\http-error-ws\ocpp_asgi\app.py", line 130, in handler
    context: RouterContext = self._create_context(
  File "C:\Users\s******5\PycharmProjects\http-error-ws\ocpp_asgi\app.py", line 232, in _create_context
    http_event = json.loads(event["body"])
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\s******5\PycharmProjects\http-error-ws\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\s******5\PycharmProjects\http-error-ws\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[run_asgi - 409] Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\s******5\PycharmProjects\http-error-ws\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\s******5\PycharmProjects\http-error-ws\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\s******5\PycharmProjects\http-error-ws\ocpp_asgi\app.py", line 100, in __call__
    await self.handler(scope, receive, send)
  File "C:\Users\s******5\PycharmProjects\http-error-ws\ocpp_asgi\app.py", line 130, in handler
    context: RouterContext = self._create_context(
  File "C:\Users\s******5\PycharmProjects\http-error-ws\ocpp_asgi\app.py", line 232, in _create_context
    http_event = json.loads(event["body"])
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\s******5\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:57535 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
```

**Comment by villekr** [comment]
This is fixed in https://github.com/villekr/ocpp-asgi/pull/10. Now if http request has no body then return http 400 and handle that gracefully.

**Comment by ChaitanyaYeole02** [comment]
@villekr Giving a version number would be easy for everyone to track.
